version: "3"

services:
  app:
    build: ./
    container_name: app
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
    restart: always
    links:
      - mysql
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testapp     
    ports:
      - "3306:3306"
