version: "3"

services:
  app:
    build: ./
    container_name: app
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
    restart: always
    links:
      - mysql
  mysql:
    image: mysql:5
    container_name: mysql
    volumes: 
      - ./MYSQL_DATABASE:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testapp     
    ports:
      - "3306:3306"
  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    ports:
      - 8989:8989
